### ISSUE TITLE
How to use it to change ProductName/legalcopyright, etc.

### ISSUE THREAD

**Issue by Ivshti** [felicienfrancois/node-resourcehacker#1]
Hello, how can I use reshacker to change resources in versioninfo? 

I tried

```
./node_modules/resourcehacker/lib/ResHacker -modify "test.exe", "test.exe", "Test Name", "VERSIONINFO", "ProductName"
```

And several other iterations of that but I couldn't get it working

**Comment by felicienfrancois** [comment]
node-resourcehacker is a simple wrapper around resourcehacker.
I don't know how to do that.

You may find more information in the `./node_modules/resourcehacker/bin/Help/help.html` file shipped with resourcehacker.
You can also use the gui (just launch the exe) to find the correct path / Variable to change
