### ISSUE TITLE
State & license of this project

### ISSUE THREAD

**Issue by Rameshv** [felicienfrancois/node-resourcehacker#2]
HI,
   Thanks for the good work. I am planning on integrating this library with electron-packager https://github.com/maxogden/electron-packager/issues/30. But based on the resource hacker licencing terms, its clearly stated that

`This software is not to be distributed via  any website domain or any other media without 
  the prior written approval of the copyright owner.`

based on this comment https://github.com/mllrsohn/node-webkit-builder/issues/44#issuecomment-51233048 , you already sent a mail to the author of the resource hacker. I am wondering is this taken care of?

 If not, instead of packaging the resourcehacker.exe with this library, we can do a npm post hook to download and install the resourcehacker.exe. This will avoid the licencing issues i suppose. 

Please let me know if you need any help, i am already working on the npm post hook stuff. 

Cheers

**Comment by felicienfrancois** [comment]
Hi Rameshv. I sent an email to the author but I never got any answer.

Your solution seems fine to me, I'll review the pull request and publish a new version in the next hours

**Comment by felicienfrancois** [comment]
Merged and published to npm

**Comment by felicienfrancois** [comment]
I just hope it wont overload his server :S

**Comment by Rameshv** [comment]
Cheers @felicienfrancois. lets hope not :)
