### ISSUE TITLE
Insecure resource download over HTTP

### ISSUE THREAD

**Issue by JacksonGL** [felicienfrancois/node-resourcehacker#5]
node-resourcehacker downloads executables [using HTTP](https://github.com/felicienfrancois/node-resourcehacker/blob/13f71e9e0c46788f6eff5a7e82b6fa11a0a3dde4/scripts/install.js#L4), which is vulnerable to the man-in-the-middle attack. It would be safer if the package were downloaded from a public HTTPS server.

**Comment by felicienfrancois** [comment]
Resourcehacker is a freeware which license dissalow distributing the software without authorisation from the author (Angus Johnson).
I contacted him some time ago and I have not received any answer. So for the time being we're not authorised to distribute the software. We can only download it from the official download links.
Sadly, the official download link is not SSL enabled.

Feel free to [contact Angus Johnson](http://www.angusj.com) to raise your issue and ask him to provide an https download link.
