### ISSUE TITLE
This is literally the most useless npm package on the internet

### ISSUE THREAD

**Issue by MelerEcckmanLawler** [felicienfrancois/node-resourcehacker#7]
There is literally no reason to use this package over `require('child_process').execFile` to execute `ResourceHacker.exe` with command line paramters, given that the download part of the installation process fails and this repo provides sparse, incomplete instructions on how to even use it (the official documentation is terrible but still better).

**Comment by felicienfrancois** [comment]
This is literally the most useless opened issue on the internet.
=> Closing

Feel free to:
- Ask questions if you want information (on why this package is useful and for who for example)
- Contribute to the code and documentation by making pull request
- Tell us what kind of frustation made you become a troll
